name: flutternotes
description: A flutter note taking application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13
  firebase_analytics: ^9.1.6
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  test: ^1.21.1

flutter:
  uses-material-design: true
